### PR TITLE
Bug 1118847: Resize app when window resolution changes.

### PR DESCRIPTION
**Pull request by Osmose**
Resizes the canvas when the viewport size changes. Adds a new signal for modes to register onResize callbacks, and updates the Topics view to reposition properly when a resize happens.

### CODE REVIEW

**Comment by Osmose** [comment]
@pmclanahan r?

**Comment by pmclanahan** [comment]
Sorry. PTO today. I'll get to this soon.

**Comment by pmclanahan** [comment]
The code looks good. Pulled it down and tried it and the resize seems to be throwing things off the page.



I see all 4 topics when I refresh, then the above when I resize a little.

**Comment by Osmose** [comment]
Pushed an update that uses the large-size layout on resize if the viewport is big enough. Should fix the issue you were seeing.

**Comment by pmclanahan** [comment]
Last thing is that resizing while on the checklist view doesn't seem to resize or reposition elements appropriately. Switching to vitals then resizing fixes things. You said in meeting, "may need to fire resize event when switching views."

**Comment by Osmose** [comment]
Amended the commit to include resizing logic for the checklist view, as well as handling repositioning the topics view when switching to it.

Also added a new commit that fixes the scrolling issues, as it depends on the work for fixing the resizing.

**Comment by pmclanahan** [comment]
Works great from here!! :shipit: :+1:

**Pull request merged**
