### PR TITLE
update country-date.json using mr data converter

### PR DESCRIPTION
**Pull request by schalkneethling**
@gegoryjost r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling spot checking these seem okay.

Can you go into what this PR addressed?

**Comment by schalkneethling** [comment]
@ckprice it is a test of how well the script works converting the data fromthe spreadsheet to JSON. As there were some 'errors' in the JSON, I did this so that Greg can have a look at the result and see if it generates what he would expect.

So, if this is good, we can merge and if there are changes to the spreadsheet in future, we can confidently keep using the script instead of me making the changes by hand.

**Comment by gregoryjost** [comment]
From what I can see (reviewed a dozen of countries), mr data converter seems more accurate. I haven't found a single discrepancy with the source spreadsheet yet.

I see a bunch of occurrences where the previous method seems to deviate by +/- 1 on some scores for some reason (some of those have already been fixed on prod).

**Comment by schalkneethling** [comment]
@gregoryjost If you are happy with the data as it is in the PR, I can go ahead and merge and this will then be pushed to production.

**Pull request closed without merging**
