### PR TITLE
Fix Bug 1133082, fixes to bar, column and grouped charts

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling thanks!

*Double bar chart*
updated code: http://cl.ly/image/40003D3c2r2J
original designs: https://bug1113249.bugzilla.mozilla.org/attachment.cgi?id=8565667

This is really great. Can we add a bit of spacing/lessen the font a bit? Looks kind of crammed compared to the design

*Column chart*
updated code: http://cl.ly/image/2D1k1f0x3j0y

Looks like some of the y-axis text is getting cut off at the top, otherwise this looks good.

*Stacked chart*
http://cl.ly/image/0G3I02422S3B

Looks great, except last line is getting dropped to the next row. Can we make this scroll?

*Line graph*
http://cl.ly/image/0c2L1D1p0R1i

Dates are getting cut off at the bottom. Also, the plot dots don't really match up with any of the dates; they seem pretty random.

**Comment by schalkneethling** [comment]
@ckprice thanks for the feedback:

First off, this PR is only related to the new bar charts so not any of the line charts. Will handle that separate from this. Now for the feedback:

Double bar
Interestingly it is not so cramped for me, but let me space it out a bit.

Column chart
Not seeing that here either ;( but, I can adjust the top margin to be sure.

The stacked chart is still the original, I am assuming we want to replace this with a new stacked chart? For me the last line does not drop off though, hmmmm

What screen res are you testing this at? I am using 2048 x 1280 on a retina display.

**Comment by schalkneethling** [comment]
This is what I see for the common languages chart.

screen shot 2015-04-28 at 20 50 21

**Comment by schalkneethling** [comment]
And here is how I see the platform independence one:

screen shot 2015-04-28 at 20 55 14

Wonder if it is not a CSS caching issue? I changed some of the charts CSS in this PR as well as margins.

**Comment by ckprice** [comment]
k, let's r+!

**Comment by ckprice** [comment]
@schalkneethling 

>The stacked chart is still the original, I am assuming we want to replace this with a new stacked chart? For me the last line does not drop off though, hmmmm

You are 100% correct here, my fault, thanks Schalk!

**Pull request merged**
