### PR TITLE
Fix Bug 1158368, add correct infographic to security issue modal

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling 

Hope this isn't a cache thing, but Surveillance (http://cl.ly/image/1h3v0q391I00) is using the same opacity for all circles. Security (http://cl.ly/image/1M0Y3t3i002n) seems to be changing. The spec is to keep them all the same opacity per Surveillance.

**Comment by schalkneethling** [comment]
@ckprice no cache ;) so, according to the data sheet there are meant to be different shades for the different categories and thus the additional need here for a legend. I know there was the bug for surveillance but, did not know that this actually referred to all 'bubble' charts.

**Comment by gregoryjost** [comment]
@schalkneethling @ckprice: surveillance and security actually use this template in two different ways.  

For security, we need to differentiate between different types of threats. We grouped them into categories and need the shades + legend to reflect that. We don't need numbers here.

For surveillance, shades are optional we don't need them so the current mono-shade is fine with me. What we do need here is numbers (from 1 at 12:00 to 8 at 11:00) so readers follow a chronological order.

**Comment by schalkneethling** [comment]
@gregoryjost Thanks, will update this PR so numbering is configurable.

**Comment by schalkneethling** [comment]
@ckprice @gregoryjost updated

**Comment by ckprice** [comment]
@gregoryjost r?

image 2015-04-29 at 11 39 13 am

**Comment by ckprice** [comment]
I will fix the surveillance order in another PR.

**Comment by gregoryjost** [comment]
Let's r.

**Comment by ckprice** [comment]
I think that's an r+ @schalkneethling! :ship:

**Pull request merged**
