### PR TITLE
Fix Bug 1133087, develop grouped bar chart, convert languages infographic

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling we have a design for this bug in [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1133087#c1). Can we work to match that?

I do think the style here could help to make your work on the standard bar chart [PR](https://github.com/mozilla/lorax/pull/45) look more like the design [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1133082#c3).

**Comment by schalkneethling** [comment]
Yes, essentially the same issues as with the standard bar chart.

**Comment by schalkneethling** [comment]
Oh yeah, completely forgot it is horizontal.

**Comment by schalkneethling** [comment]
@ckprice WIP but open for review.

**Comment by schalkneethling** [comment]
I am aware that the groups of bars are way to close together. That is what I am working on right now.

**Comment by schalkneethling** [comment]
This is of course an alternate option to the design.

**Comment by ckprice** [comment]
@schalkneethling r+ with the caveat that we do have to address both this double bar horizontal graph and the vertical single bar graph  to match designs.

Thanks!

**Comment by schalkneethling** [comment]
Agreed

**Pull request merged**
