### PR TITLE
Fix Bug 1149779, update modal issue styling

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice This is currently still WIP, just wanted to have it open so you can start having a look at the changes that has been made and provide any feedback there may be.

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey @ckprice - I would really love to get this one merged today so I can start focusing on the individual infographics. Let me know, thanks!

**Comment by ckprice** [comment]
Hey Schalk, thought it was still WIP. Will check it out this AM.

-- 
Cory Price
/ckprice

**Comment by ckprice** [comment]
@schalkneethling can you update the font colors to match? Primary color should be white, with black being used for the 'WHAT MOZ/YOU CAN DO' body copy.

image 2015-04-10 at 8 30 04 am

**Comment by schalkneethling** [comment]
@ckprice - with those colors we fail the WCAG guidelines [http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html] for color contrast, this is why I changed it to all black. We can play with it in some scenarios i.e. use some other colors, and with some of the graphs the white and black contrast nicely but, with the text, it's gotta be black.

See http://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=DB3F33 vs. http://snook.ca/technical/colour_contrast/colour.html#fg=000000,bg=DB3F33

**Comment by gregoryjost** [comment]
@schalkneethling - can we stick to the original design for now? I would like to revisit this issue as part of a larger and concerted effort to enhance the overall design in the future (have a few ideas around that). But for now, I am reluctant to deconstruct the original look&feel further than we already have.

Adding this to our wishlist for v2.

**Comment by schalkneethling** [comment]
Well, one of the areas where the site does not do well is accessibility and color contrast as one of the factors. The idea was to resolve as many of these issues as possible as part of the other bugs we work on. I will change this back, but we should really reconsider the color choices here as white clearly fails with regards to contrast of text to background.

The fact that the background is not completely opaque makes it even worse.

**Comment by schalkneethling** [comment]
Having changed the colors back as requested and, in the interest of moving forward I am going to go ahead and merge this. If there is anything that we need to change or revert to, we can do that easily enough in a follow on pull request.

**Pull request merged**
