### PR TITLE
Fix Bug 1133827, update civility inofgraphic

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling the first two blocks are stacking on top of each other. Are they suppose to go side by side?

image 2015-04-30 at 11 19 44 am

**Comment by schalkneethling** [comment]
@ckprice yeah, check caching of the CSS but, I will also have a look.

**Comment by schalkneethling** [comment]
@ckprice ok, fixed.

**Comment by ckprice** [comment]
@schalkneethling looks much better, r+!

**Pull request merged**
