### PR TITLE
Fix Bug 1156363, show source for infographic when set.

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling links should open in a new window.

Also, not sure if this is just from this bug, but I'm no longer able to scroll down in Chrome on longer infographics. FF looks okay. Let me know if you want to fix it in this bug, or if I should open a new one.

**Comment by schalkneethling** [comment]
@ckprice let's merge this. I will open a bug for opening in new tab/window

I cannot repro the scrolling issue though.

**Comment by schalkneethling** [comment]
@ckprice can you consistently reproduce the scrolling issue?

**Comment by ckprice** [comment]
@schalkneethling note: this is happening on production for me, so not specific to this PR.

> can you consistently reproduce the scrolling issue?

Uhm, on some infographics and not others.

https://shapeoftheweb.mozilla.org/access/accessible
Happens _most_ times on this one.

https://shapeoftheweb.mozilla.org/trust/security
Seems to scroll okay most times.

Again, Chrome specific.

Let's table this. r+

**Comment by schalkneethling** [comment]
@ckprice let's open a bug to track that though. Thanks!

**Comment by ckprice** [comment]
@schalkneethling okay! Opened as a P3 (not req for launch). https://bugzilla.mozilla.org/show_bug.cgi?id=1158863

**Pull request merged**
