### PR TITLE
Fix Bug 1161323, populate ad tracking infographic

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r? This does not have the different colors for the bars but, there is a separate bug to take care of that.

### CODE REVIEW

**Comment by ckprice** [comment]
Thanks Schalk! I switched it to display the tracker instead of Company name in the below mock.

@gregoryjost we talked about changing the color of these bar graphs as a nice to have, and we'll look as a P3. Please confirm this look is good to go for launch.

image 2015-05-06 at 12 08 33 pm

**Comment by gregoryjost** [comment]
Ok but let's look at colors for bars and line charts (not just this one) as our first P3 starting tomorrow please. I don't think users will be able to tell who those trackers belong to without colors.

Before we merge this:
- seeing "ga.com" on the graph (1st item), but it should be "google-analytics.com".
- in the title: can we change "80.13%" to "80%"?

**Comment by ckprice** [comment]
@gregoryjost looks like it goes past the bounds of the line chart if we use the full name.

image 2015-05-06 at 1 15 44 pm

We have about 10-12 characters of space to use on that first entry. Any recommendations without having to update the dimensions of the graph?

**Comment by gregoryjost** [comment]
can we tweak the angle and/or font size?

**Comment by gregoryjost** [comment]
Or better, invert the angle? 135 instead of 225 degrees (or 16:30 vs 19:30)?

**Comment by gregoryjost** [comment]
Something like this? http://grab.by/H482

**Comment by schalkneethling** [comment]
Based on email conversation I am merging this and will make tweaks in a follow on PR. Thanks!

**Pull request merged**
