### PR TITLE
Fix Bug 1133096, remove tags, and related interactions and screens

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice @pmclanahan r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling I think the hope was to keep the "Tag" dots around the globe to give the explore view some structure. We would then disable the hover/click actions. It doesn't look like much of a circle without the smaller dots around the outside.

**Comment by schalkneethling** [comment]
@ckprice I will dig deeper and try to find if it is possible to keep them without having events attached to them. I have some idea, but not 100% confident.

The other thing to consider is the impact on performance when we are drawing a bunch of things that have no purpose. There is currently some dots drawn in a 'fakeItems' loop but, the recent change of dropping the 'circles' that relates to tags has made a real change in CPU usage and thus performance.

I will therefore not suggest we just re-introduce them without taking the above in account.

With that said, perhaps we can look at drawing more fake items and see how that affects the overall canvas?

**Comment by ckprice** [comment]
@schalkneethling your points make sense, and I've passed our recommendation to Gregory.

In the meantime, @alexgibson/@jpetto do you think you could give the JS a review? This doesn't need much review on the files which were added/removed, more of things that were changed.

**Comment by alexgibson** [comment]
Just a friendly ping to say this hasn't gone unnoticed - I'm slightly snowed under this week, but hopefully I can get round to looking at this soon :+1:

**Comment by alexgibson** [comment]
Code changes look fine to me - I'm not familiar with the code base, but I ran this locally and nothing blows up :boom: :+1: I did a quick grep through the project for some of the removed directives/models etc, and looks good.

I agree if there's CPU savings to be had, then not having to continually redraw superfluous dots might be a worthwhile compromise.

So, r+ from me :cactus: 

P.S - I did notice a scrolling bug on my iPhone but it's not related to this change. I will file a bug (think I also know the cause).

**Comment by alexgibson** [comment]
I opened #20 to fix the random bug I noticed. Hooray for 1 line fixes :smile:

**Comment by schalkneethling** [comment]
@alexgibson Thanks!

**Pull request merged**
