### PR TITLE
[fix bug 1133824] Remove numbers, adjust JSON to rotate back

### PR DESCRIPTION
**Pull request by ckprice**
@schalkneethling banged my head against the wall to figure out  how to rotate bubbles back. In the end, just rotated JSON. r?

### CODE REVIEW

**Comment by gregoryjost** [comment]
The numbers are mixed up. Here is the right order:
1. Avertising
2. No scarcity
3. Data collection
4. Data storage
5. Government access
6. Surveillance
7. Lack of regulation
8. Further entrenched

**Comment by gregoryjost** [comment]
Don't think you did anything wrong Cory, they were mixed up to being with when the numbers were coded on top.

**Comment by ckprice** [comment]
@gregoryjost ah, thanks for catching. Updated.

r?

image 2015-05-06 at 3 48 15 pm

**Comment by schalkneethling** [comment]
r+ from me

**Comment by schalkneethling** [comment]
Based on the comment in https://github.com/mozilla/lorax/pull/73#issuecomment-99632366 and the follow on screen shot in https://github.com/mozilla/lorax/pull/73#issuecomment-99634363 this is good to merge.

**Pull request merged**
