### PR TITLE
Fix Bug 1163812, open about modal on ecosystem, vitals and checklist views

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@gregoryjost when the about modal is opened in checklist view, it covers the issue list. Is this okay?

image 2015-06-08 at 12 23 07 pm

**Comment by gregoryjost** [comment]
It's true it doesn't work great on this view. If you guys agree, I suggest we only add the panel to vitals. This way we can still test vitals as a landing candidate, checklist is unlikely to be used for that purpose so I am comfortable not having it there.

**Comment by ckprice** [comment]
SGTM.

@schalkneethling can you please remove checklist from the views that show the about modal on landing?

Thanks

**Comment by schalkneethling** [comment]
Done, merging. Thanks!

**Pull request merged**
