### PR TITLE
Fix Bug 1133824, updates to surveillance infographic

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r? Not sure of the numbering is in the correct order so, let me know if it needs changing.

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling getting a warning running `grunt server`

> Running "less:server" (less) task
FileError: 'infographics/surveillance.less' wasn't found in src/styles/main.less on line 25, column 1:
24 @import 'infographics/data-portability';
25 @import 'infographics/surveillance';
26
Warning: Error compiling src/styles/main.less Use --force to continue.
Aborted due to warnings.

**Comment by schalkneethling** [comment]
hmmm, the file is part of the commit. Not happening for me.... will have a look. I need to rebase this one with master anyhow.

**Comment by schalkneethling** [comment]
@ckprice ok, rebased and tested again locally. All looks fine on my side.

**Comment by schalkneethling** [comment]
@ckprice does this work for you now?

**Comment by ckprice** [comment]
@schalkneethling yes r+!

**Pull request merged**
