### PR TITLE
Fix Bug 1133089, update landing page experience

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice @pmclanahan r?

* Remove the last three lines from the Legend modal describing the dots and lines [happens in https://github.com/mozilla/bedrock/pull/2810]
* Move the content in the About modal into the Legend modal.
* Remove the About modal
* Remove the About icon on the bottom left 
* There should now be just one modal/icon on the homepage, and it should come in from the left
* When the user first visits the home page for this session, load it with the Legend/About modal extended.

### CODE REVIEW

**Comment by ckprice** [comment]
Thanks @schalkneethling! Reviewed it with Gregory and we have some notes.

1. Please remove the bottom 3 lines of the legend

image 2015-03-04 at 11 54 49 am

2. Please update the font to `font-size: 1.6em` and `line-height: 24px` for the side panel copy? In the paragraphs, not the headings.

3. [nice to have but not required] Can the modal slide out _after_ the globe has 'exploded'? Right now the timing is almost the same.

**Comment by schalkneethling** [comment]
1. That happens separately on bedrock see https://github.com/mozilla/bedrock/pull/2810
2. will do
3. I will look into this, currently it uses some Angular 'magic' so, you litterally just say true or false, not sure if there is a property to add that will specify a delay.

**Comment by ckprice** [comment]
Per Greg today, let's punt on #3 above.

@pmclanahan can you give this JS/CSS a review?

**Comment by pmclanahan** [comment]
@ckprice if it's doing what you think it should I think we're good. The code itself looks good but I've not run it since I know you both have been doing that. I'm ready to just merge and we can see it live.

**Comment by ckprice** [comment]
@schalkneethling this runs just like it should locally - r+!

**Pull request merged**
