### PR TITLE
Fix Bug 114436, add vitals description text to canvas

### PR DESCRIPTION
**Pull request by schalkneethling**
@ckprice r?

### CODE REVIEW

**Comment by ckprice** [comment]
@schalkneethling text is cut off in responsive view

Image of CloudApp

**Comment by schalkneethling** [comment]
@ckprice yes, I saw that. Thing is, the canvas in general does not behave very well in terms of responsiveness so, perhaps we should handle that as one big fix separately?

**Comment by schalkneethling** [comment]
Basically I want to move forward as fast as possible to get through as many bugs, in terms of the infographics, as we can, before we get stuck in to anything that may turn out to be pretty big.

**Comment by ckprice** [comment]
@schalkneethling is it possible to remove the line for responsive?

**Comment by ckprice** [comment]
I opened [bug 1154314](https://bugzilla.mozilla.org/show_bug.cgi?id=1154314) to track misc responsive fixes not necessarily blockers for April.

**Comment by schalkneethling** [comment]
@ckprice "is it possible to remove the line for responsive?" - which line are you referring to? not sure which line ;)

**Comment by ckprice** [comment]
@schalkneethling "These are the four..."

**Comment by schalkneethling** [comment]
@ckprice oh, then we can just close the PR and not merge it. That is all this adds.

**Comment by ckprice** [comment]
r+! Responsiveness for the tagline added to bug 1154314 (P3)

**Pull request merged**
